version: 2

sources:
  - name: unclustered
    database: cost_optimization_test
    schema: raw  
    tables:
      - name: raw_customers
      - name: raw_orders
        config: 
          freshness:
            warn_after: {count: 7, period: day}
          loaded_at_field: O_ORDERDATE

  - name: tpch_100
    database: snowflake_sample_data
    schema: tpch_sf100
    tables:
      - name: lineitem
      - name: nation 
      - name: region